### PR TITLE
upgrade `dua` to latest version in benchmarks

### PR DESCRIPTION
**Pull request by Byron**
I love seeing the benchmarks run by CI and would wonder if the latest version of `dua` shows a different result.

Thank you.

### CODE REVIEW

**Review by KSXGitHub — CHANGES_REQUESTED** [review]
Please update the dua version in README.md as well

**Review by KSXGitHub — APPROVED** [review]

**Comment by KSXGitHub** [comment]
CI is running: https://github.com/KSXGitHub/parallel-disk-usage/actions/runs/4270704122

**Comment by KSXGitHub** [comment]
A new version is released. Go to this [link](https://github.com/KSXGitHub/parallel-disk-usage/releases/tag/0.8.5), download `benchmark-reports.tar.gz`, extract the archive, and view `tmp.benchmark-report.CHARTS.md` (with a markdown viewer).

**Comment by Byron** [comment]
Thanks for your help!

Screenshot 2023-02-25 at 20 53 36

Amazing, basically no change. It would be interesting to figure the reason for that one day, a 2x improvement would certainly be interesting in principle. Oh well :).

**Comment by KSXGitHub** [comment]
Unless you have made substantial changes to data structure, there is no reason to expect visible improvements.

**Comment by KSXGitHub** [comment]
Furthermore, I guess that `pdu` is faster because it does less work. It does not handle reflinks, for example.

**Comment by KSXGitHub** [comment]
@Byron Your `dua` suddenly went up to third place in the [latest benchmarks](https://ksxgithub.github.io/parallel-disk-usage-0.10.0-benchmarks/tmp.benchmark-report.CHARTS.html) even though its version stays the same.

**Comment by Byron** [comment]
Thanks for the heads-up - probably I should re-install it as well.
And after doing so I thought I'd see something like `rayon` being updated, but that was not the case. So no idea what's going on there.

**Pull request merged**
